# Copy this configuration to: ~/.dblab/engine/configs/server.yml
# Configuration reference guide: https://postgres.ai/docs/reference-guides/database-lab-engine-configuration-reference
server:
  verificationToken: "thunboo_token"
  port: 2345
  disableConfigModification: false

embeddedUI:
  enabled: true
  dockerImage: "postgresai/ce-ui:latest"
  host: "0.0.0.0"
  port: 2346

global:
  engine: postgres
  debug: true
  database:
    username: postgres
    dbname: postgres

poolManager:
  mountDir: /var/lib/dblab
  dataSubDir: data
  clonesMountSubDir: clones
  socketSubDir: sockets
  observerSubDir: observer
  preSnapshotSuffix: "_pre"
  selectedPool: ""

databaseContainer: &db_container
  dockerImage: "pg-1c-ru-centos-rpms:v2"
  envs:
    PG_MAJOR: 17
  containerConfig:
    "shm-size": 1gb

databaseConfigs: &db_configs
  configs:
    shared_buffers: 1GB
    shared_preload_libraries: ""
    maintenance_work_mem: "500MB"
    work_mem: "100MB"
    lc_messages: "en_US.UTF-8"
    lc_monetary: "ru_RU.UTF-8"
    lc_numeric: "ru_RU.UTF-8"
    lc_time: "ru_RU.UTF-8"
    max_connections: 100
    default_text_search_config: 'pg_catalog.russian'

provision:
  <<: *db_container
  portPool:
    from: 6000
    to: 6099
  useSudo: false
  keepUserPasswords: false
  cloneAccessAddresses: "0.0.0.0"

retrieval:
  refresh:
    timetable: "0 0 * * 1"
    skipStartRefresh: false
  jobs:
    - logicalDump
    - logicalRestore
    - logicalSnapshot
  spec:
    logicalDump:
      options:
        dockerImage: "pg-dblab-ru:v2"
        <<: *db_container
        dumpLocation: "/var/lib/dblab/dblab_pool/dump"

        envs:
          PG_MAJOR: 17
        source:
          type: remote
          connection:
            dbname: postgres
            host: 100.125.59.64
            port: 5556
            username: postgres
            password: postgres

        databases:

        parallelJobs: 4


        customOptions:

    logicalRestore:
      options:
        dockerImage: "pg-dblab-ru:v2"
        <<: *db_container
        dumpLocation: "/var/lib/dblab/dblab_pool/dump"
        envs:
          PG_MAJOR: 17
        parallelJobs: 4
        <<: *db_configs

        databases:

        queryPreprocessing:
          queryPath: ""
          maxParallelWorkers: 2
          inline: ""

        customOptions:
          - "--no-tablespaces"
          - "--no-privileges"
          - "--no-owner"
          - "--exit-on-error"

        skipPolicies: true

    logicalSnapshot:
      options:
        <<: *db_configs
        preprocessingScript: ""
        databaseRename:
        envs:
          PG_MAJOR: 17
        dataPatching:
          <<: *db_container
          dockerImage: "pg-dblab-ru:v2"
          queryPreprocessing:
            queryPath: ""
            maxParallelWorkers: 2
            inline: ""

cloning:
  accessHost: "localhost"
  maxIdleMinutes: 120
  protectionLeaseDurationMinutes: 1440
  protectionMaxDurationMinutes: 10080
  protectionExpiryWarningMinutes: 1440

diagnostic:
  logsRetentionDays: 7

observer:

webhooks:

platform:
  url: "https://postgres.ai/api/general"
  enableTelemetry: true

